version: "3.9"

services:
  backend:
    build:
      context: ./blog-backend
    container_name: blog-backend
    ports:
      - "4000:4000"
    volumes:
      - ./blog-backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017/blog
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mongo
      - redis
    networks:
      - blog-network

  redis:
    image: redis:7
    container_name: redis
    networks:
      - blog-network

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27018:27017"  # external host port is 27018, internal is 27017
    volumes:
      - mongo-data:/data/db
    networks:
      - blog-network

volumes:
  mongo-data:

networks:
  blog-network:
    driver: bridge


